# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('traffic-control', ['core', 'network'])
    module.source = [
      'model/traffic-control-layer.cc',
      'model/packet-filter.cc',
      'model/queue-disc.cc',
      'model/pfifo-fast-queue-disc.cc',
      'model/red-queue-disc.cc',
      'model/codel-queue-disc.cc',
      'model/fq-codel-queue-disc.cc',
      'model/pie-queue-disc.cc',
      'model/MyPipeline.cc',
      'model/IvyPipeline.cc',
      'model/IvyPipeline_rr.cc',
      'model/IvyPipeline_sp.cc',
      'model/MyScheduling.cc',
      # 'model/MyPipeline_limited.cc',
      'model/SimplePIFO.cc',
      'model/vPIFO.cc',
      'model/vPIFO_limited.cc',
      'model/IvyPIFO.cc',
      'model/IvyPIFO_rr.cc',
      'model/IvyPIFO_sp.cc',
      'helper/traffic-control-helper.cc',
      'helper/queue-disc-container.cc'
        ]

    module_test = bld.create_ns3_module_test_library('traffic-control')
    module_test.source = [
      'test/red-queue-disc-test-suite.cc',
      'test/codel-queue-disc-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'traffic-control'
    headers.source = [
      'model/traffic-control-layer.h',
      'model/packet-filter.h',
      'model/queue-disc.h',
      'model/pfifo-fast-queue-disc.h',
      'model/red-queue-disc.h',
      'model/codel-queue-disc.h',
      'model/fq-codel-queue-disc.h',
      'model/pie-queue-disc.h',
      'model/MyPipeline.h',
      'model/IvyPipeline.h',
      'model/IvyPipeline_rr.h',
      'model/IvyPipeline_sp.h',
      # 'model/myPipeline_limited.h',
      'model/MyScheduling.h',
      'model/SimplePIFO.h',
      'model/vPIFO.h',
      'model/vPIFO_limited.h',
      'model/IvyPIFO.h',
      'model/IvyPIFO_rr.h',
      'model/IvyPIFO_sp.h',
      'helper/traffic-control-helper.h',
      'helper/queue-disc-container.h'
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    bld.ns3_python_bindings()

